import profileVector from "@/public/assets/layout/profile-pic.png";
import { Order } from "./definitions";

export const lastOrders: Order[] = [
    {
        id: "1",
        user: "Marcus Bergson",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },
    {
        id: "2",
        user: "Jane Doe",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "3",
        user: "Jeremy Smith",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "4",
        user: "Corey Schleifer",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },
    {
        id: "5",
        user: "Cooper Press",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },
    {
        id: "6",
        user: "Phillip Lubin",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },

    {
        id: "1",
        user: "Marcus Bergson",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "2",
        user: "Jane Doe",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },
    {
        id: "3",
        user: "Jeremy Smith",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "4",
        user: "Corey Schleifer",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },
    {
        id: "5",
        user: "Cooper Press",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "6",
        user: "Phillip Lubin",
        date: "2021-06-12",
        amount: 250,
        status: "Refund",
        invoice: "download",
    },

    {
        id: "1",
        user: "Marcus Bergson",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "2",
        user: "Jane Doe",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "3",
        user: "Jeremy Smith",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "4",
        user: "Corey Schleifer",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "5",
        user: "Cooper Press",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
    {
        id: "6",
        user: "Phillip Lubin",
        date: "2021-06-12",
        amount: 250,
        status: "Paid",
        invoice: "download",
    },
];
